# .goreleaser.yml
# Build customization
builds:
  - binary: storyview
    goos:
      - darwin
    goarch:
      - amd64
archive:
  format: tar.gz
  replacements:
    darwin: macOS
brew:
  github:
    owner: mcordell
    name: homebrew-storyview

  commit_author:
    name: Michael Cordell
    email: surpher@gmail.com

  folder: Formula

  description: "View JIRA issue's branches, PRs, and Builds in one command"
